const foods = [
  {name:"Chicken Adobo", calories:250, protein:25, category:"Ulam"},
  {name:"Pork Adobo", calories:320, protein:24, category:"Ulam"},
  {name:"Beef Caldereta", calories:350, protein:28, category:"Ulam"},
  {name:"Menudo", calories:280, protein:20, category:"Ulam"},
  {name:"Afritada", calories:290, protein:23, category:"Ulam"},
  {name:"Mechado", calories:330, protein:26, category:"Ulam"},
  {name:"Bistek Tagalog", calories:300, protein:28, category:"Ulam"},
  {name:"Kare-Kare", calories:400, protein:20, category:"Ulam"},
  {name:"Lechon Kawali", calories:450, protein:30, category:"Ulam"},
  {name:"Crispy Pata", calories:550, protein:32, category:"Ulam"},

  {name:"Sinigang na Baboy", calories:220, protein:20, category:"Sabaw"},
  {name:"Sinigang na Hipon", calories:180, protein:22, category:"Sabaw"},
  {name:"Tinola", calories:210, protein:24, category:"Sabaw"},
  {name:"Bulalo", calories:320, protein:25, category:"Sabaw"},
  {name:"Nilaga", calories:260, protein:24, category:"Sabaw"},
  {name:"La Paz Batchoy", calories:400, protein:18, category:"Sabaw"},
  {name:"Mami", calories:300, protein:15, category:"Sabaw"},
  {name:"Lomi", calories:380, protein:20, category:"Sabaw"},
  {name:"Arroz Caldo", calories:250, protein:14, category:"Sabaw"},
  {name:"Sopas", calories:270, protein:12, category:"Sabaw"},

  {name:"Rice (1 cup)", calories:200, protein:4, category:"Carbs"},
  {name:"Garlic Rice", calories:230, protein:4, category:"Carbs"},
  {name:"Brown Rice", calories:215, protein:5, category:"Carbs"},
  {name:"Java Rice", calories:250, protein:4, category:"Carbs"},
  {name:"Fried Rice", calories:280, protein:6, category:"Carbs"},
  {name:"Pancit Canton", calories:350, protein:12, category:"Carbs"},
  {name:"Pancit Bihon", calories:300, protein:10, category:"Carbs"},
  {name:"Pancit Malabon", calories:420, protein:16, category:"Carbs"},
  {name:"Palabok", calories:390, protein:14, category:"Carbs"},
  {name:"Spaghetti Pinoy", calories:380, protein:13, category:"Carbs"},

  {name:"Bangus", calories:220, protein:26, category:"Seafood"},
  {name:"Daing na Bangus", calories:280, protein:28, category:"Seafood"},
  {name:"Inihaw na Tilapia", calories:200, protein:24, category:"Seafood"},
  {name:"Fried Tilapia", calories:270, protein:22, category:"Seafood"},
  {name:"Shrimp", calories:140, protein:24, category:"Seafood"},
  {name:"Calamares", calories:290, protein:16, category:"Seafood"},
  {name:"Fish Fillet", calories:250, protein:20, category:"Seafood"},
  {name:"Escabeche", calories:230, protein:20, category:"Seafood"},
  {name:"Rellenong Bangus", calories:300, protein:25, category:"Seafood"},
  {name:"Tuna Steak", calories:210, protein:30, category:"Seafood"},

  {name:"Turon", calories:180, protein:2, category:"Snacks"},
  {name:"Banana Cue", calories:200, protein:2, category:"Snacks"},
  {name:"Camote Cue", calories:210, protein:2, category:"Snacks"},
  {name:"Fishball", calories:150, protein:5, category:"Street Food"},
  {name:"Kwek-Kwek", calories:170, protein:6, category:"Street Food"},
  {name:"Siomai", calories:180, protein:8, category:"Street Food"},
  {name:"Isaw", calories:190, protein:12, category:"Street Food"},
  {name:"Betamax", calories:140, protein:10, category:"Street Food"},
  {name:"Tokneneng", calories:200, protein:8, category:"Street Food"},
  {name:"Squid Ball", calories:160, protein:6, category:"Street Food"}
];
{name:"Lumpiang Shanghai", calories:250, protein:10, category:"Snacks"},
{name:"Lumpiang Ubod", calories:180, protein:5, category:"Snacks"},
{name:"Fresh Lumpia", calories:200, protein:6, category:"Snacks"},
{name:"Empanada", calories:280, protein:8, category:"Snacks"},
{name:"Okoy", calories:190, protein:7, category:"Snacks"},
{name:"Ukoy", calories:200, protein:8, category:"Snacks"},
{name:"Cheese Sticks", calories:220, protein:7, category:"Snacks"},
{name:"Nachos Pinoy", calories:350, protein:9, category:"Snacks"},
{name:"Cassava Cake", calories:300, protein:4, category:"Dessert"},
{name:"Bibingka", calories:280, protein:6, category:"Dessert"},

{name:"Puto", calories:120, protein:3, category:"Dessert"},
{name:"Kutsinta", calories:110, protein:2, category:"Dessert"},
{name:"Sapin-Sapin", calories:180, protein:3, category:"Dessert"},
{name:"Biko", calories:230, protein:4, category:"Dessert"},
{name:"Maja Blanca", calories:190, protein:3, category:"Dessert"},
{name:"Leche Flan", calories:250, protein:5, category:"Dessert"},
{name:"Halo-Halo", calories:320, protein:7, category:"Dessert"},
{name:"Mais Con Yelo", calories:240, protein:4, category:"Dessert"},
{name:"Saging con Yelo", calories:230, protein:3, category:"Dessert"},
{name:"Ube Halaya", calories:220, protein:3, category:"Dessert"},

{name:"Taho", calories:180, protein:8, category:"Dessert"},
{name:"Ice Cream Ube", calories:220, protein:4, category:"Dessert"},
{name:"Mango Float", calories:300, protein:4, category:"Dessert"},
{name:"Brazo de Mercedes", calories:280, protein:5, category:"Dessert"},
{name:"Yema Cake", calories:320, protein:6, category:"Dessert"},
{name:"Polvoron", calories:140, protein:2, category:"Dessert"},
{name:"Pastillas", calories:120, protein:2, category:"Dessert"},
{name:"Buchi", calories:160, protein:3, category:"Dessert"},
{name:"Turon with Langka", calories:220, protein:2, category:"Dessert"},
{name:"Minatamis na Saging", calories:190, protein:2, category:"Dessert"},

{name:"Coke", calories:140, protein:0, category:"Drinks"},
{name:"Sprite", calories:130, protein:0, category:"Drinks"},
{name:"Royal", calories:150, protein:0, category:"Drinks"},
{name:"Iced Tea", calories:120, protein:0, category:"Drinks"},
{name:"Milk Tea", calories:350, protein:3, category:"Drinks"},
{name:"Buko Juice", calories:90, protein:1, category:"Drinks"},
{name:"Sago't Gulaman", calories:180, protein:0, category:"Drinks"},
{name:"Calamansi Juice", calories:70, protein:0, category:"Drinks"},
{name:"Mango Shake", calories:220, protein:2, category:"Drinks"},
{name:"Avocado Shake", calories:280, protein:4, category:"Drinks"},

{name:"Kapeng Barako", calories:5, protein:0, category:"Drinks"},
{name:"3-in-1 Coffee", calories:110, protein:1, category:"Drinks"},
{name:"Hot Chocolate", calories:160, protein:3, category:"Drinks"},
{name:"Yakult", calories:50, protein:1, category:"Drinks"},
{name:"Protein Shake", calories:180, protein:25, category:"Drinks"},
{name:"Ginataang Bilo-Bilo", calories:310, protein:5, category:"Dessert"},
{name:"Champorado", calories:280, protein:7, category:"Dessert"},
{name:"Milo", calories:110, protein:3, category:"Drinks"},
{name:"Energen", calories:130, protein:4, category:"Drinks"},
{name:"Gatorade", calories:90, protein:0, category:"Drinks"}
{name:"Tapsilog", calories:520, protein:28, category:"Breakfast"},
{name:"Tocilog", calories:550, protein:24, category:"Breakfast"},
{name:"Longsilog", calories:580, protein:22, category:"Breakfast"},
{name:"Bangsilog", calories:490, protein:30, category:"Breakfast"},
{name:"Hotsilog", calories:530, protein:18, category:"Breakfast"},
{name:"Cornsilog", calories:500, protein:20, category:"Breakfast"},
{name:"Chicksilog", calories:570, protein:28, category:"Breakfast"},
{name:"Porksilog", calories:620, protein:32, category:"Breakfast"},
{name:"Liemposilog", calories:650, protein:35, category:"Breakfast"},
{name:"Sisilog", calories:600, protein:28, category:"Breakfast"},

{name:"Egg (Boiled)", calories:70, protein:6, category:"Breakfast"},
{name:"Egg (Fried)", calories:90, protein:6, category:"Breakfast"},
{name:"Scrambled Egg", calories:100, protein:7, category:"Breakfast"},
{name:"Omelette", calories:150, protein:10, category:"Breakfast"},
{name:"Pandesal", calories:120, protein:4, category:"Breakfast"},
{name:"Spanish Bread", calories:180, protein:4, category:"Breakfast"},
{name:"Ensaymada", calories:220, protein:5, category:"Breakfast"},
{name:"Monay", calories:150, protein:4, category:"Breakfast"},
{name:"Pan de Coco", calories:180, protein:4, category:"Breakfast"},
{name:"Cheese Bread", calories:200, protein:5, category:"Breakfast"},

{name:"Ginisang Monggo", calories:220, protein:14, category:"Vegetables"},
{name:"Pinakbet", calories:180, protein:6, category:"Vegetables"},
{name:"Chopsuey", calories:160, protein:7, category:"Vegetables"},
{name:"Laing", calories:190, protein:5, category:"Vegetables"},
{name:"Tortang Talong", calories:180, protein:8, category:"Vegetables"},
{name:"Ginataang Kalabasa", calories:200, protein:4, category:"Vegetables"},
{name:"Adobong Kangkong", calories:90, protein:3, category:"Vegetables"},
{name:"Ginisang Ampalaya", calories:100, protein:4, category:"Vegetables"},
{name:"Ensaladang Talong", calories:80, protein:2, category:"Vegetables"},
{name:"Steamed Vegetables", calories:70, protein:3, category:"Vegetables"},

{name:"Balut", calories:190, protein:14, category:"Street Food"},
{name:"Penoy", calories:140, protein:12, category:"Street Food"},
{name:"Adidas", calories:160, protein:10, category:"Street Food"},
{name:"Helmet", calories:120, protein:9, category:"Street Food"},
{name:"Chicken Skin", calories:250, protein:12, category:"Street Food"},
{name:"Proben", calories:220, protein:15, category:"Street Food"},
{name:"Dynamite", calories:180, protein:6, category:"Street Food"},
{name:"Cheese Lumpia", calories:170, protein:5, category:"Street Food"},
{name:"Kikiam", calories:160, protein:6, category:"Street Food"},
{name:"Tempura", calories:150, protein:7, category:"Street Food"},

{name:"Burger Steak", calories:350, protein:20, category:"Ulam"},
{name:"Chicken Fillet", calories:280, protein:22, category:"Ulam"},
{name:"Fried Chicken", calories:320, protein:25, category:"Ulam"},
{name:"Chicken BBQ", calories:290, protein:26, category:"Ulam"},
{name:"Pork BBQ", calories:300, protein:24, category:"Ulam"},
{name:"Inasal", calories:310, protein:28, category:"Ulam"},
{name:"Sisig", calories:420, protein:25, category:"Ulam"},
{name:"Dinuguan", calories:260, protein:20, category:"Ulam"},
{name:"Paksiw na Isda", calories:170, protein:22, category:"Seafood"},
{name:"Ginataang Isda", calories:250, protein:20, category:"Seafood"},
{name:"Bicol Express", calories:420, protein:20, category:"Regional"},
{name:"Kinilaw", calories:160, protein:22, category:"Regional"},
{name:"Chicken Binakol", calories:240, protein:24, category:"Regional"},
{name:"Piaparan", calories:310, protein:18, category:"Regional"},
{name:"Pastil", calories:350, protein:20, category:"Regional"},
{name:"Chicken Pastil", calories:330, protein:22, category:"Regional"},
{name:"Pianggang", calories:340, protein:25, category:"Regional"},
{name:"Piyanggang Manok", calories:350, protein:26, category:"Regional"},
{name:"Pancit Batil Patong", calories:420, protein:18, category:"Regional"},
{name:"Pancit Habhab", calories:390, protein:15, category:"Regional"},

{name:"Ginataang Hipon", calories:250, protein:22, category:"Seafood"},
{name:"Garlic Butter Shrimp", calories:300, protein:24, category:"Seafood"},
{name:"Buttered Garlic Crab", calories:350, protein:28, category:"Seafood"},
{name:"Grilled Squid", calories:180, protein:22, category:"Seafood"},
{name:"Stuffed Squid", calories:260, protein:20, category:"Seafood"},
{name:"Sizzling Squid", calories:280, protein:18, category:"Seafood"},
{name:"Ginataang Alimasag", calories:330, protein:25, category:"Seafood"},
{name:"Steamed Fish", calories:160, protein:24, category:"Seafood"},
{name:"Fish Sinigang", calories:180, protein:22, category:"Seafood"},
{name:"Fish Tinola", calories:190, protein:20, category:"Seafood"},

{name:"Canton Guisado", calories:350, protein:14, category:"Noodles"},
{name:"Bam-I", calories:380, protein:16, category:"Noodles"},
{name:"Misua", calories:180, protein:7, category:"Noodles"},
{name:"Sotanghon Soup", calories:220, protein:8, category:"Noodles"},
{name:"Chicken Sotanghon", calories:260, protein:16, category:"Noodles"},
{name:"Pancit Molo", calories:240, protein:12, category:"Noodles"},
{name:"Pancit Luglug", calories:360, protein:14, category:"Noodles"},
{name:"Chicken Noodles", calories:290, protein:15, category:"Noodles"},
{name:"Seafood Noodles", calories:320, protein:18, category:"Noodles"},
{name:"Instant Pancit Canton", calories:290, protein:6, category:"Noodles"},

{name:"Lugaw", calories:180, protein:5, category:"Merienda"},
{name:"Goto", calories:220, protein:10, category:"Merienda"},
{name:"Tokwa't Baboy", calories:280, protein:18, category:"Merienda"},
{name:"Siopao", calories:250, protein:10, category:"Merienda"},
{name:"Siopao Asado", calories:260, protein:11, category:"Merienda"},
{name:"Siopao Bola-Bola", calories:280, protein:12, category:"Merienda"},
{name:"Pichi-Pichi", calories:150, protein:2, category:"Merienda"},
{name:"Palitaw", calories:130, protein:2, category:"Merienda"},
{name:"Carioca", calories:140, protein:2, category:"Merienda"},
{name:"Maruya", calories:200, protein:3, category:"Merienda"},

{name:"Ginataan", calories:230, protein:4, category:"Dessert"},
{name:"Nilupak", calories:210, protein:3, category:"Dessert"},
{name:"Binatog", calories:190, protein:5, category:"Dessert"},
{name:"Puto Bumbong", calories:220, protein:4, category:"Dessert"},
{name:"Mamon", calories:170, protein:4, category:"Dessert"},
{name:"Mamón Toasted", calories:180, protein:4, category:"Dessert"},
{name:"Otap", calories:160, protein:3, category:"Dessert"},
{name:"Barquillos", calories:140, protein:2, category:"Dessert"},
{name:"Rosquillos", calories:150, protein:2, category:"Dessert"},
{name:"Biscocho", calories:170, protein:3, category:"Dessert"},
{name:"Jollibee Chickenjoy", calories:320, protein:24, category:"Fast Food"},
{name:"Jollibee Burger Steak", calories:280, protein:16, category:"Fast Food"},
{name:"Jollibee Spaghetti", calories:330, protein:10, category:"Fast Food"},
{name:"Jollibee Yum Burger", calories:290, protein:12, category:"Fast Food"},
{name:"McDo Chicken", calories:310, protein:24, category:"Fast Food"},
{name:"McDo Burger", calories:300, protein:13, category:"Fast Food"},
{name:"McSpaghetti", calories:320, protein:10, category:"Fast Food"},
{name:"Chowking Siomai", calories:190, protein:8, category:"Fast Food"},
{name:"Chowking Chao Fan", calories:410, protein:14, category:"Fast Food"},
{name:"Mang Inasal PM1", calories:520, protein:30, category:"Fast Food"},

{name:"Green Mango", calories:70, protein:1, category:"Fruits"},
{name:"Mango", calories:100, protein:1, category:"Fruits"},
{name:"Banana", calories:110, protein:1, category:"Fruits"},
{name:"Apple", calories:95, protein:0, category:"Fruits"},
{name:"Orange", calories:80, protein:1, category:"Fruits"},
{name:"Pineapple", calories:85, protein:1, category:"Fruits"},
{name:"Watermelon", calories:50, protein:1, category:"Fruits"},
{name:"Papaya", calories:60, protein:1, category:"Fruits"},
{name:"Melon", calories:55, protein:1, category:"Fruits"},
{name:"Avocado", calories:240, protein:3, category:"Fruits"},

{name:"Boiled Chicken Breast", calories:180, protein:35, category:"Gym Food"},
{name:"Grilled Chicken Breast", calories:190, protein:36, category:"Gym Food"},
{name:"Boiled Egg Whites", calories:70, protein:14, category:"Gym Food"},
{name:"Tuna in Water", calories:120, protein:26, category:"Gym Food"},
{name:"Greek Yogurt", calories:130, protein:15, category:"Gym Food"},
{name:"Oatmeal", calories:150, protein:6, category:"Gym Food"},
{name:"Peanut Butter", calories:190, protein:8, category:"Gym Food"},
{name:"Whey Protein", calories:130, protein:25, category:"Gym Food"},
{name:"Protein Bar", calories:220, protein:20, category:"Gym Food"},
{name:"Cottage Cheese", calories:110, protein:12, category:"Gym Food"},

{name:"Sweet Potato", calories:120, protein:2, category:"Healthy"},
{name:"Boiled Corn", calories:100, protein:3, category:"Healthy"},
{name:"Mixed Salad", calories:90, protein:3, category:"Healthy"},
{name:"Caesar Salad", calories:220, protein:8, category:"Healthy"},
{name:"Chicken Salad", calories:250, protein:20, category:"Healthy"},
{name:"Steamed Broccoli", calories:55, protein:4, category:"Healthy"},
{name:"Steamed Carrots", calories:45, protein:1, category:"Healthy"},
{name:"Steamed Beans", calories:50, protein:2, category:"Healthy"},
{name:"Tofu", calories:100, protein:10, category:"Healthy"},
{name:"Tokwa", calories:110, protein:11, category:"Healthy"},

{name:"Almonds", calories:170, protein:6, category:"Healthy"},
{name:"Cashew", calories:180, protein:5, category:"Healthy"},
{name:"Trail Mix", calories:200, protein:6, category:"Healthy"},
{name:"Rice Cake", calories:60, protein:1, category:"Healthy"},
{name:"Dark Chocolate", calories:170, protein:2, category:"Healthy"},
{name:"Low Fat Milk", calories:100, protein:8, category:"Healthy"},
{name:"Soy Milk", calories:110, protein:7, category:"Healthy"},
{name:"Fresh Buko", calories:80, protein:1, category:"Healthy"},
{name:"Boiled Saba", calories:120, protein:1, category:"Healthy"},
{name:"Homemade Smoothie", calories:180, protein:8, category:"Healthy"}
];
