const foods = [
  {name:"Chicken Adobo", calories:250, protein:25, category:"Ulam"},
  {name:"Pork Adobo", calories:320, protein:24, category:"Ulam"},
  {name:"Beef Caldereta", calories:350, protein:28, category:"Ulam"},
  {name:"Menudo", calories:280, protein:20, category:"Ulam"},
  {name:"Afritada", calories:290, protein:23, category:"Ulam"},
  {name:"Mechado", calories:330, protein:26, category:"Ulam"},
  {name:"Bistek Tagalog", calories:300, protein:28, category:"Ulam"},
  {name:"Kare-Kare", calories:400, protein:20, category:"Ulam"},
  {name:"Lechon Kawali", calories:450, protein:30, category:"Ulam"},
  {name:"Crispy Pata", calories:550, protein:32, category:"Ulam"},

  {name:"Sinigang na Baboy", calories:220, protein:20, category:"Sabaw"},
  {name:"Sinigang na Hipon", calories:180, protein:22, category:"Sabaw"},
  {name:"Tinola", calories:210, protein:24, category:"Sabaw"},
  {name:"Bulalo", calories:320, protein:25, category:"Sabaw"},
  {name:"Nilaga", calories:260, protein:24, category:"Sabaw"},
  {name:"La Paz Batchoy", calories:400, protein:18, category:"Sabaw"},
  {name:"Mami", calories:300, protein:15, category:"Sabaw"},
  {name:"Lomi", calories:380, protein:20, category:"Sabaw"},
  {name:"Arroz Caldo", calories:250, protein:14, category:"Sabaw"},
  {name:"Sopas", calories:270, protein:12, category:"Sabaw"},

  {name:"Rice (1 cup)", calories:200, protein:4, category:"Carbs"},
  {name:"Garlic Rice", calories:230, protein:4, category:"Carbs"},
  {name:"Brown Rice", calories:215, protein:5, category:"Carbs"},
  {name:"Java Rice", calories:250, protein:4, category:"Carbs"},
  {name:"Fried Rice", calories:280, protein:6, category:"Carbs"},
  {name:"Pancit Canton", calories:350, protein:12, category:"Carbs"},
  {name:"Pancit Bihon", calories:300, protein:10, category:"Carbs"},
  {name:"Pancit Malabon", calories:420, protein:16, category:"Carbs"},
  {name:"Palabok", calories:390, protein:14, category:"Carbs"},
  {name:"Spaghetti Pinoy", calories:380, protein:13, category:"Carbs"},

  {name:"Bangus", calories:220, protein:26, category:"Seafood"},
  {name:"Daing na Bangus", calories:280, protein:28, category:"Seafood"},
  {name:"Inihaw na Tilapia", calories:200, protein:24, category:"Seafood"},
  {name:"Fried Tilapia", calories:270, protein:22, category:"Seafood"},
  {name:"Shrimp", calories:140, protein:24, category:"Seafood"},
  {name:"Calamares", calories:290, protein:16, category:"Seafood"},
  {name:"Fish Fillet", calories:250, protein:20, category:"Seafood"},
  {name:"Escabeche", calories:230, protein:20, category:"Seafood"},
  {name:"Rellenong Bangus", calories:300, protein:25, category:"Seafood"},
  {name:"Tuna Steak", calories:210, protein:30, category:"Seafood"},

  {name:"Turon", calories:180, protein:2, category:"Snacks"},
  {name:"Banana Cue", calories:200, protein:2, category:"Snacks"},
  {name:"Camote Cue", calories:210, protein:2, category:"Snacks"},
  {name:"Fishball", calories:150, protein:5, category:"Street Food"},
  {name:"Kwek-Kwek", calories:170, protein:6, category:"Street Food"},
  {name:"Siomai", calories:180, protein:8, category:"Street Food"},
  {name:"Isaw", calories:190, protein:12, category:"Street Food"},
  {name:"Betamax", calories:140, protein:10, category:"Street Food"},
  {name:"Tokneneng", calories:200, protein:8, category:"Street Food"},
  {name:"Squid Ball", calories:160, protein:6, category:"Street Food"}
];
